{application,landet,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{landet_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[landet,landet_app,landet_device,landet_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
